config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated :user do
    root to: 'splashs#index'
  end

  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  resources :user do
    resources :categories, only: %i[index new show create destroy] do
      resources :transactions, only: %i[index new show create destroy]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Category
    can :create, Category
    can :write, Category

    can :read, Transaction
    can :create, Transaction

    return unless user.present?

    can :destroy, Category, user: user
    can :destroy, Transaction, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :transactions, foreign_key: 'category_id', class_name: 'Transaction'

  validates :name, presence: true, length: { maximum: 255 }
  has_one_attached :icon

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :transactions

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.includes(:user, :transactions).order(created_at: :desc)
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    if @category.save
      flash[:notice] = 'Category successfully created!'
      redirect_to user_categories_path(@category.user_id)
    else
      flash[:notice] = 'An error occured while adding a category!'
      render :new
    end
  end

  def edit; end

  def update; end

  def destroy; end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splashs_controller.rb
class SplashsController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_transaction, only: %i[edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @transaction = Transaction.where(category_id: params[:category_id]).order(created_at: :desc)
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
    @category = Category.where(user_id: current_user.id)
  end

  def create
    @user = current_user
    @transaction = @user.transactions.new(transaction_params)
    if @transaction.save
      flash[:notice] = 'Transaction sucessfully created!'
      redirect_to user_category_transactions_path(@user)
    else
      flash[:alert] = 'Transaction could not be be created!'
      render :new
    end
  end

  def destroy
    # puts plain: params
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    flash[:notice] = 'Transaction was successfully deleted.'
    redirect_to user_category_transactions_path
  end

  private

  def set_transaction
    @transaction = Transaction.includes(:user, :categories).find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splashs_helper.rb
module SplashsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_category.html.erb
<%= stylesheet_link_tag('try')  %>
<div>
<section class= "category_card">

<div class="category-data">
<div class="iimg-icon">
<%= image_tag category.icon, skip_pipeline: true, class:'icon'%>
</div>
<div class="name-date">
<h2 class= "category_name"> <%= category.name %></h2>
 <span class="bottom_data">
      <time data="<%= category.created_at %>" class="date"> DATE: <%= category.created_at.strftime("%e %B %Y") %></time>
 </span>
 </div>
<span class= "category_total"><%= number_to_currency(category.total_amount)%></span>
</div>
</section> 
</div> 

app/views/categories/index.html.erb
<header>
<h1 class="category-title">Categories</h1>
</header>

<main>
 <% if @categories.any? %>
  <% @categories.each do |category| %>
  <%= link_to render(category), user_category_transactions_url(current_user, category.id), class: 'category_wrapper'%> 
<% end %> 
 <% else %>
 <p style="margin-top: 50px; text-align:center; color: orange; font-weight:bold;">
    There is no category added yet!
  </p>
<% end %>
</main>

<footer class="footer">
<%= link_to "Add a new category", new_user_category_path(current_user), class: "add-cat" %>
</footer>

app/views/categories/new.html.erb
<%= form_with model: @category, :html => { :style => "width: 76%; margin: auto; gap: 10px;  border: 1px solid #eee;" }, url: user_categories_path,local: true, data: {turbo:false}  do |form| %>
 
  <div style= "margin-bottom: 20px;    margin-bottom: 20px; display: flex; flex-direction: column;">
  <%= image_tag('user.png', style:'width: 200px; height: 200px; margin: auto;') %>
    <%= form.file_field :icon, class: "form-control w-50", placeholder: "Image or Icon", style: "margin-top: 26px;  margin: auto;" %>
  </div> 
  <div>
    <%= form.text_field :name, class: "form-control w-50", placeholder: "Name" , style: ' padding: 10px; margin: auto;' %>
  </div>
    <div class="text-center m-3">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
    <% if @category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this group from being saved:</h2>
  
        <ul>
          <% @category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

app/views/categories/show.html.erb
<nav class="navbar bg-primary">
    <div class="container-fluid d-flex align-items-baseline">
      <%= link_to :back do %>
        <i class="fas fa-arrow-left text-white fs-5 px-2"></i>
      <% end %>
      <h6 class="text-white">Transactions</h6>
      <% if user_signed_in? %>   
        <%= button_to "Sign out", destroy_user_session_path, :method => :delete, class: 'btn-primary border border-0'%>
      <% end %>
    </div>
  </nav>

  <div class="border border-1 d-flex m-2">
    <img src="<%= @category.icon %>" width="80px"/>
    <h3 class="m-2"><%= @category.name %></h3>
    <div class="ms-auto pt-5 pe-3 fw-bolder">
       $<%= @category.transactions.inject(0) { |sum, e| sum + (e.amount) }%>
    </div>
  </div>

<div id="groups">
  <% @category.transactions.each do |entity| %>
    <%= link_to entity, class: "text-reset text-decoration-none" do %>
    <div class="border border-1 d-flex mx-4 my-3">
      <h3 class="m-2"><%= entity.name %></h3>
      <h3 class="ms-auto me-2 mt-2">$<%= entity.amount %></h3>
    </div>
      <%= button_to 'Delete ', user_category_url(id: category.id), method: :delete,  data: {turbo: false}, class: 'btn-category' %>
    <% end %>
  <% end %>
</div>
<p style="color: green"><%= notice %></p>
<div class="fixed-bottom">
  <%= link_to "Add New Transaction", new_user_category_transaction_path(current_user.id, @category.id), class: "w-100 btn btn-lg btn-success" %>
</div

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light " style ="background: #3778c2; height: 80px">
  <%= link_to 'Budget Calculator', root_path, style: "text-decoration: none; color: #eeee; font-size: 30px; font-weight: 600; padding-left: 20px;" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse nav-trans nav-right justify-content-end" id="navbarNav">
    <ul class="navbar-nav me-auto" style= "flex-direction: row; width: 100%;justify-content: end; padding-right: 120px;">
      <li class="nav-item">
      <%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn bg-danger text-light"  %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splashs/index.html.erb
<%= stylesheet_link_tag('try')  %>
<section class="splash-screen">
<h1 class= "tittle">Budget Calculator</h1>
<div class= "splash-div">
<%= link_to 'Log-in', user_session_path, class: 'sign-btn' %>
<%= link_to 'Sign up', new_user_registration_path, class: 'sign-btn'%>
</div>
</section>

app/views/transactions/index.html.erb
<%= stylesheet_link_tag('try')  %>
<section class="container-fluid my-4">
    <div class="row">
        <div class="col-12 my-1">
            <%= link_to raw('<i class="fa-solid fa-angle-left fa-2x"></i>'), root_path %>
            <h1 class="text-primary d-flex justify-content-center">TRANSACTIONS</h1>
             
        </div>
        <div class="col-12">
            <h3 class="d-flex justify-content-center py-2 px-5">
            </h3>
        </div>
        </div>
        <div class="col-12 container">
            <p class="text-primary d-flex justify-content-start">
                <% if @category.name.present? %>
                <h3 class="text-primary"><%= @category.name %></h3>
                <% end %>
            </p>
            <h4 class="d-flex justify-content-end " style= "margin-bottom: 15px; color: #434b54;"> Total Amount:
                <%= Transaction.where(category_id: @category.id).reduce(0) { |sum, t| sum + t.amount+0.0}  %></h4>
         </div>
  <div class="container ">
    <% @transaction.each do |t|  %>
        <%= link_to(user_category_transaction_path(id: t.id), style: "text-decoration: none;") do %>

            <div class="  budget-item1 my-2 " style=" display: flex; padding: 5px; justify-content: space-between; border: none !important;box-shadow: -12px -6px 21px 8px #eee; height: auto; margin-bottom : 40px;">
               <div class="my-4 cat-icon col-3 d-flex justify-content-between trans-img-div">
                 <%= image_tag(@category.icon, style:" width : 120px; height : 120px; text-decoration: none;") %>
               </div>
               <div class="d-column col-4 " style="display: flex; align-items : center; flex-direction: column; ">
                  <h4 class="my-4" style= "text-decoration: none; color: #434b54; text-transform: capitalize;"><%= t.name %></h4>
                   <p class="my-4" style= "text-decoration: none; color: lightblue;"><%= l t.created_at.to_date, format: :long %></p>
               </div>
               <div class="col-3">
                    <p class="my-4" style= "text-decoration: none; color : yellowgreen; font-weight: 600; font-size: 20px;">K<%= t.amount+0.0 %></p>
                </div>
                
             </div>
       <% end %>
    <% end %>
  </div>
</section>
<footer class="footer">
<%= link_to "Add Transaction", new_user_category_transaction_path, class: "add-trans" %>
<%= link_to "Back", root_path, class: "add-trans", style: "margin-left: 10px; " %>
</footer>
           

app/views/transactions/new.html.erb
<div class="container-fluid">
    <div class="row d-flex justify-content-center">
        <div class="col-12 my-4">
            <%= link_to raw('<i class="fa-solid fa-angle-left fa-2x"></i>'), root_path %>
           </div>
        <div class="col-12 d-flex justify-content-center">
            <% if @transaction.errors.any?  %>
            <%= raw('<h6 class="text-center">Because: </h6>') %>
            <div class="d-coulumn justify-content-center">
                <% @transaction.errors.full_messages.each_with_index do |message, index|%>
                <br><p class="d-column justify-content-start"><%=  index+1 %>. <%= message %> </p>
               <%end%>
            </div>
          <%end%>
        </div>
        <div class="col-md-6  card p-4 m-5">
           <%=  form_with model:  @transaction, url: user_category_transactions_path, data: { turbo:false } do |f| %>
           <%= f.text_field :name, placeholder:'Trnsaction Name', class: 'form-control p-3 my-3'%>
           <%= f.number_field :amount,  placeholder: 'Amount', min:'0',  class: 'form-control p-3 my-3'%>
           <div class="form-control p-3 my-3">
            <%= f.label :category %>
            <%= f.collection_select :category_id, Category.where(user_id: current_user.id).order(:name),:id,:name %>
          </div>
           <div class="d-flex justify-content-end">
            <%= f.submit "Save", disable_with: 'Submiting...', class:'btn btn-success p-3 d-flex justify-content-end' %>
           </div>
           <% end %>
        </div>
    </div>
</div>

app/views/transactions/show.html.erb
<div class= "transaction" style="display: flex;
flex-direction: column;
justify-content: center;
align-items: center;
border: 1px solid #eee;
height: 300px;
background: #eee;
width: 50%;
margin: auto;">
<span style="font-size: 30px; color: #000; text-transform: capitalize; font-weight: 600; margin-bottom: 20px;"><%= @transaction.name%></span>
<span style="font-size: 15px; color: gray; text-transform: capitalize; font-weight: 400; margin-bottom: 10px;">DATE: <%= @transaction.created_at.strftime("%e %B %Y") %></span>
<span style="font-size: 15px; color: gray; text-transform: capitalize; font-weight: 400; margin-bottom: 10px;">TOTAL PAYMENT: K<%= (@transaction.amount) %></span>
<% if can? :destroy, @transaction %>
<div>
 <%= button_to 'Delete', user_category_transaction_path(id: @transaction.id), method: :delete,  data: {turbo: false}, class: 'btn bg-danger', style: "color: white; margin-bottom: 10px;" %>
 </div>
 <% end %>
</div>